services:
  RC-psql:
    container_name: "RC-psql"
    image: bitnami/postgresql:14
    expose:
      - 5432
    ports:
      - 5432:5432
    network_mode: "host"
    environment:
      POSTGRES_DB: "RC"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      ALLOW_IP: 0.0.0.0/0
    volumes:
      - RC_psql:/bitnami/postgresql

  RC-pgadmin:
    container_name: 'RC-pgadmin'
    image: dpage/pgadmin4
    ports:
      - 5555:80
    depends_on:
      - RC-psql
    network_mode: host
    environment:
      PGADMIN_DEFAULT_EMAIL: 'postgres@shadow.com'
      PGADMIN_DEFAULT_PASSWORD: 'password'
      PGADMIN_CONFIG_LOGIN_BANNER: '"Email: postgres@shadow.com Pass: password"'
    volumes:
      - RC_pgadmin:/var/lib/pgadmin

volumes:
  RC_psql:
  RC_pgadmin: